### ISSUE TITLE
Not OS friendly (Windows) compatible

### ISSUE THREAD

**Issue by slopez15** [joeyism/node-minify-all#2]
Suggest using path.join() (it is OS friendly). If you did, Probably a npm standard for global installation folder is different than linux. 

ERROR INFO::
C:\Users\user\path\0. update>minify-all ./ zip
found file: ai.js
C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\node_modules\node-minify\lib\node-minify.js:161
          throw new Error('Type does not exist');
          ^

Error: Type does not exist
    at Object.compress (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\node_modules\node-minify\lib\node-minify.js:161:17)
    at Object.minify (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\node_modules\node-minify\lib\node-minify.js:83:10)
    at C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\index.js:30:13
    at C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\index.js:14:13
    at Array.forEach (native)
    at walk (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\index.js:10:36)
    at minifyAll (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\index.js:25:5)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\index.js:45:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

C:\Users\user\path\0. update>minify-all ./
found file: ai.js
C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\node_modules\node-minify\lib\node-minify.js:104
          throw new Error(bin + ' not found !');
          ^

Error: uglifyjs not found !
    at getPath (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\node_modules\node-minify\lib\node-minify.js:104:17)
    at Object.compress (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\node_modules\node-minify\lib\node-minify.js:132:27)
    at Object.minify (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\node_modules\node-minify\lib\node-minify.js:83:10)
    at C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\index.js:30:13
    at C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\index.js:14:13
    at Array.forEach (native)
    at walk (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\index.js:10:36)
    at minifyAll (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\index.js:25:5)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\index.js:45:5)
    at Module._compile (module.js:570:32)

C:\Users\user\path\0. update>minify-all .
found file: ai.js
C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\node_modules\node-minify\lib\node-minify.js:104
          throw new Error(bin + ' not found !');
          ^

Error: uglifyjs not found !
    at getPath (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\node_modules\node-minify\lib\node-minify.js:104:17)
    at Object.compress (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\node_modules\node-minify\lib\node-minify.js:132:27)
    at Object.minify (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\node_modules\node-minify\lib\node-minify.js:83:10)
    at C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\index.js:30:13
    at C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\index.js:14:13
    at Array.forEach (native)
    at walk (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\index.js:10:36)
    at minifyAll (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\index.js:25:5)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\minify-all\index.js:45:5)
    at Module._compile (module.js:570:32)

**Comment by joeyism** [comment]
Ah, that's a good catch. Do you want to fix it and submit a merge request? I don't have a windows machine

**Comment by AndresInSpace** [comment]
Can you supply a fix for this? Running into same issue.

**Comment by joeyism** [comment]
I don't have a windows machine, so I can't test it. If you (or anyone) want to submit a merge request, I'd gladly accept it

**Comment by SiemvandenBerg** [comment]
Hello, maybe you could update the readme on the front page that this is not Windows friendly. I'm getting the same error when trying to minify some css by cli.
